import path from 'node:path';
import fs from 'node:fs/promises';
import { safeWrite } from '../../utils/fileUtils.js';
import logger from '../../utils/logger.js';
import pluralize from 'pluralize';

const importRegex = /import\s+(\w+)\s+from\s+['"]\.\/routes\/(\w+)\.routes\.js['"]/gi;
const useRegex = /app\.use\(\s*['"]\/api\/(\w+)['"]\s*,\s*(\w+)\s*\);/gi;

const generateStartupLogger = (apiPrefix) => {
  return `
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log('\\n cfapi-generated MongoDB API is now running!\\n');
  console.log(\` Environment     : \${process.env.NODE_ENV || 'development'}\`);
  console.log(\` Base URL        : http://localhost:\${PORT}${apiPrefix}\`);
  console.log(\` Swagger Docs    : http://localhost:\${PORT}/api-docs\`);
  console.log('\\n  Generated by cfapi CLI tool');
});`.trim();
};

const writeServerFile = async (models, outputDir, includeStartup = false) => {
  const filePath = path.join(outputDir, 'server.js');
  const API_PREFIX = '/api';

  let existingContent = '';
  try {
    existingContent = await fs.readFile(filePath, 'utf-8');
  } catch {
    existingContent = '';
  }

  const existingImports = new Map();
  const existingUses = new Set();

  let match;
  while ((match = importRegex.exec(existingContent)) !== null) {
    const modelName = match[2].toLowerCase();
    const importVar = match[1];
    existingImports.set(modelName, importVar);
  }

  while ((match = useRegex.exec(existingContent)) !== null) {
    const routePath = match[1].toLowerCase(); 
    existingUses.add(routePath);
  }

  const newImportLines = [];
  const newUseLines = [];

  for (const model of models) {
    const lower = model.toLowerCase();
    const routePath = pluralize(lower); 
    const routeVar = `${lower}Routes`;

    if (!existingImports.has(lower)) {
      newImportLines.push(`import ${routeVar} from './routes/${model}.routes.js';`);
      existingImports.set(lower, routeVar);
    }

    if (!existingUses.has(routePath)) {
      newUseLines.push(`app.use('${API_PREFIX}/${routePath}', ${routeVar});`);
      existingUses.add(routePath); 
    }
  }

  const dynamicOpenApiLoader = `
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
let openApiDocument = {};
try {
  openApiDocument = require('./openapi.json');
} catch (e) {
  console.error(" Failed to load OpenAPI document:", e.message);
}`.trim();

  const dotenvImport = `import dotenv from 'dotenv';`;
  const connectDbImport = `import connectDB from './config/db.js';`;

  // === CASE: Create new file ===
  if (!existingContent) {
    const baseContent = `import express from 'express';
${dotenvImport}
import swaggerUi from 'swagger-ui-express';
import cors from 'cors';
${connectDbImport}
${newImportLines.join('\n')}

${dynamicOpenApiLoader}

dotenv.config();
connectDB();

const app = express();
app.use(cors());
app.use(express.json());
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openApiDocument));

${newUseLines.join('\n')}

app.get('/', (req, res) => {
  res.send(' cfapi-generated MongoDB API is running');
});

${includeStartup ? generateStartupLogger(API_PREFIX) : ''}`;

    await safeWrite(filePath, baseContent, 'server.js');
    logger.info(' Created new MongoDB server.js with initial routes');
    return;
  }

  // === CASE: Update existing file ===

  // Remove old static OpenAPI import
  existingContent = existingContent.replace(
    /import\s+openApiDocument\s+from\s+['"]\.\/openapi\.json['"]\s*;?/g,
    ''
  );

  // Remove old app.listen() block
  existingContent = existingContent.replace(
    /const\s+PORT\s*=\s*process\.env\.PORT[\s\S]+?app\.listen\([^}]+\}\);?/gs,
    ''
  );

  // Add dynamic OpenAPI loader if not present
  if (!existingContent.includes('openApiDocument =')) {
    const dotenvIndex = existingContent.indexOf('dotenv.config();');
    if (dotenvIndex !== -1) {
      existingContent =
        existingContent.slice(0, dotenvIndex) +
        `${dynamicOpenApiLoader}\n\n` +
        existingContent.slice(dotenvIndex);
    }
  }

  // Insert dotenv import if missing
  if (!existingContent.includes(`import dotenv from`)) {
    const insertIndex = existingContent.indexOf('import swaggerUi');
    existingContent =
      existingContent.slice(0, insertIndex) +
      `${dotenvImport}\n` +
      existingContent.slice(insertIndex);
  }

  // Insert connectDB import if missing
  if (!existingContent.includes('import connectDB')) {
    const insertIndex = existingContent.indexOf('import swaggerUi');
    existingContent =
      existingContent.slice(0, insertIndex) +
      `${connectDbImport}\n` +
      existingContent.slice(insertIndex);
  }

  // Ensure dotenv.config() is present
  if (!existingContent.includes('dotenv.config();')) {
    const appInitIndex = existingContent.indexOf('const app =');
    existingContent =
      existingContent.slice(0, appInitIndex) +
      'dotenv.config();\n' +
      existingContent.slice(appInitIndex);
  }

  // Ensure connectDB() is present
  if (!existingContent.includes('connectDB();')) {
    const dotEnvIndex = existingContent.indexOf('dotenv.config();');
    existingContent =
      existingContent.slice(0, dotEnvIndex + 'dotenv.config();'.length) +
      '\nconnectDB();' +
      existingContent.slice(dotEnvIndex + 'dotenv.config();'.length);
  }

  // Inject new imports
  const importMatches = [...existingContent.matchAll(/import .+ from .+;/g)];
  const lastImportEnd = importMatches.length
    ? importMatches.at(-1).index + importMatches.at(-1)[0].length
    : 0;
  const beforeImports = existingContent.slice(0, lastImportEnd);
  const afterImports = existingContent.slice(lastImportEnd);
  const importsToInsert = newImportLines.length ? '\n' + newImportLines.join('\n') + '\n' : '';
  let updatedContent = beforeImports + importsToInsert + afterImports;

  // Inject new app.use() lines
  const appUseMatches = [...updatedContent.matchAll(/app\.use\([^)]+\);/g)];
  const lastAppUse = appUseMatches.at(-1);
  const insertUseIndex = lastAppUse
    ? updatedContent.indexOf(lastAppUse[0]) + lastAppUse[0].length
    : updatedContent.indexOf('app.use(express.json());') + 'app.use(express.json());'.length;

  const usesToInsert = newUseLines.length ? '\n' + newUseLines.join('\n') + '\n' : '';
  updatedContent =
    updatedContent.slice(0, insertUseIndex) +
    usesToInsert +
    updatedContent.slice(insertUseIndex);

  // Add startup logger if required
  if (includeStartup && !updatedContent.includes('app.listen(')) {
    updatedContent += `\n\n${generateStartupLogger(API_PREFIX)}\n`;
  }

  await safeWrite(filePath, updatedContent, 'server.js');
  logger.info(' Updated MongoDB server.js with new models');
};

export default writeServerFile;
