import express from 'express';
import dotenv from 'dotenv';
import swaggerUi from 'swagger-ui-express';
import cors from 'cors';
import userRoutes from './routes/user.routes.js';

import { createRequire } from 'module';
const require = createRequire(import.meta.url);
let openApiDocument = {};
try {
  openApiDocument = require('./openapi.json');
} catch (e) {
  console.error("Failed to load OpenAPI document:", e.message);
}

dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(openApiDocument));

app.use('/api/users', userRoutes);

app.get('/', (req, res) => {
  res.send('cfapi-generated API is running');
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log('\n cfapi-generated API is now running!\n');
  console.log(` Environment     : ${process.env.NODE_ENV || 'development'}`);
  console.log(` Base URL        : http://localhost:${PORT}/api`);
  console.log(` Swagger Docs    : http://localhost:${PORT}/api-docs`);
  console.log('\n  Generated by cfapi CLI tool');
});
